### ISSUE TITLE
Unprocessable Entity Error via Stitchdata

### ISSUE THREAD

**Issue by danwebb4** [singer-io/tap-harvest-forecast#13]
I have had a successful Harvest Forecast integration running daily via Stitchdata for a few months. Starting last week, every time the integration runs, I get the following error:

422 Client Error: Unprocessable Entity for url: https://api.forecastapp.com/assignments

I have tried refreshing the connection credentials and setting the integration up again from scratch, but am still receiving the error. I'm wondering if some configuration has changed on the Harvest Forecast side that broke this integration.

Any help or guidance you can provide is appreciated!

**Comment by lochlmond** [comment]
I'm experiencing the same issue.

**Comment by Adam-D-Lewis** [comment]
I'm also experiencing this issue.  Maybe forecast's api changed?  It is undocumented and they say they can change at any moment.  https://help.getharvest.com/forecast/faqs/faq-list/api/  Not completely sure at the moment

**Comment by Adam-D-Lewis** [comment]
@xmnlab

**Comment by cdilga** [comment]
I'm also experiencing this issue - debugging this one now

**Comment by cdilga** [comment]
Can anyone confirm whether Stitch itself is experiencing this issue?

**Comment by cdilga** [comment]
As I debug, I'll keep updating the issue.

I've been able to sync all other data except for `assignments` by removing `"selected": true` from the `catalog.json`

```
{
      "stream": "assignments",
      "tap_stream_id": "assignments",
      "schema": {
        "type": "object",
        "properties": {
          "id": {
            "type": [
              "null",
              "integer"
            ]
          },
          "start_date": {
            "type": [
              "null",
              "string"
            ],
            "format": "date-time"
          },
          "end_date": {
            "type": [
              "null",
              "string"
            ],
            "format": "date-time"
          },
          "allocation": {
            "type": [
              "null",
              "integer"
            ]
          },
          "notes": {
            "type": [
              "null",
              "string"
            ]
          },
          "updated_at": {
            "type": [
              "null",
              "string"
            ],
            "format": "date-time"
          },
          "updated_by_id": {
            "type": [
              "null",
              "integer"
            ]
          },
          "project_id": {
            "type": [
              "null",
              "integer"
            ]
          },
          "person_id": {
            "type": [
              "null",
              "integer"
            ]
          },
          "placeholder_id": {
            "type": [
              "null",
              "integer"
            ]
          },
          "repeated_assignment_set_id": {
            "type": [
              "null",
              "integer"
            ]
          },
          "active_on_days_off": {
            "type": [
              "null",
              "boolean"
            ]
          }
        },
        "additionalProperties": true
      },
      "metadata": [
        {
          "breadcrumb": [],
          "metadata": {
            "selected": true
            "table-key-properties": [
              "id"
            ],
            "valid-replication-keys": [
              "updated_at"
            ],
            "forced-replication-method": "FULL-TABLE"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "id"
          ],
          "metadata": {
            "inclusion": "automatic"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "start_date"
          ],
          "metadata": {
            "inclusion": "available"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "end_date"
          ],
          "metadata": {
            "inclusion": "available"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "allocation"
          ],
          "metadata": {
            "inclusion": "available"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "notes"
          ],
          "metadata": {
            "inclusion": "available"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "updated_at"
          ],
          "metadata": {
            "inclusion": "automatic"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "updated_by_id"
          ],
          "metadata": {
            "inclusion": "available"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "project_id"
          ],
          "metadata": {
            "inclusion": "available"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "person_id"
          ],
          "metadata": {
            "inclusion": "available"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "placeholder_id"
          ],
          "metadata": {
            "inclusion": "available"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "repeated_assignment_set_id"
          ],
          "metadata": {
            "inclusion": "available"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "active_on_days_off"
          ],
          "metadata": {
            "inclusion": "available"
          }
        }
      ]
    },

```

**Comment by xmnlab** [comment]
I saw that other lib had a similar problem.

I tried to call the API using curl and I received the following message:

´´´sh
curl -H "Authorization: Bearer  ..."      -H "Forecast-Account-Id: ..."      -H "User-Agent: Harvest-Scraper" https://api.forecastapp.com/assignments
{"errors":["start_date and end_date must be present."]}
´´´ 

´´´sh  
curl -H "Authorization: Bearer ..."      -H "Forecast-Account-Id: ..."      -H "User-Agent: Harvest-Scraper" https://api.forecastapp.com/assignments -d "start_date=2021-01-01" -d "end_data=2021-02-01"
{"error_code":500,"error_name":"Internal Server Error","message":"We're sorry, but something went wrong. The problem has been automatically reported to us and we are looking into it now. Please try again in a few minutes. Check the Harvest System Status at https://www.harveststatus.com for the latest updates."
´´´ 

checking https://www.harveststatus.com/, it seems that on March, 18th, Forecast  was unavailable. Maybe they changed something to fix the bug that changed the API

**Comment by cdilga** [comment]
Hi all, I've managed to diagnose the bug. 

Debugging the code, I see that the url being requested for `assignments` is https://api.forecastapp.com/assignments
As @xmnlab above has mentioned, doing a request without start and end date gives a 422. 

The solution will be to add in the params for start and end date

**Comment by xmnlab** [comment]
I forced the start and end date and it seems it worked.

**Comment by cdilga** [comment]
I've got some code coming shortly. I also found that a full table refresh to deal with the hard deletes will need a new pagination mechanism.

for e.g. https://api.forecastapp.com/assignments?start_date=2019-01-01&end_date=2021-03-31
```
{
  "errors": [
    "The maximum allowed timeframe is 180 days."
  ]
}
```

I think there is some pagination in the https://github.com/singer-io/tap-harvest/blob/master/tap_harvest/__init__.py

**Comment by cdilga** [comment]
For anyone who needs a real quick fix, I've hard-coded the last 180 days to load. Hopefully someone beats me to the pagination mechanism!
https://github.com/cdilga/tap-harvest-forecast/tree/hotfix/forecast-issue-13

**Comment by kevincal** [comment]
Note that I confirmed with Harvest/Forecast they made that breaking change to their API
```
Hi Kevin,

Thanks for getting in touch, and sorry for the trouble here!

I did some digging and found out our team did make some updates to Forecast recently and it's likely that's why you're now seeing an error. However, I'm afraid we still don't support the Forecast API as we've not officially released it. We didn't build the available library and there has always been a risk that the published library may break at any time due to changes we make on our end - this is also a big reason we haven't officially released a Forecast API. 

I know this isn't the answer you're hoping for, and I'm really sorry I couldn't be of more help here! Let me know if there are any other questions I can help answer.

Best,
Jillian
```

**Comment by cdilga** [comment]
I've implemented a paginator and opened a pull request.

Due to the lack of unit or end to end tests, I doubt that this will be accepted as is. 
For now, test yourself and use the code from the PR

**Comment by danwebb4** [comment]
Does anyone know when this will be up and running again via Stitch? FYI, I checked this morning, and it's now showing a different error than the original 422 error:

'dict' object has no attribute 'replication_keys'

**Comment by kevincal** [comment]
If you join the Singer Slack there is a team member there that mentioned
they are now aware of the issue and will get some visibility on it.
https://join.slack.com/t/singer-io/shared_invite/zt-gdv0h48z-ZPIFMKwtOZmcd1UzmjRncw

**Comment by danwebb4** [comment]
The 422 error is resolved, but it appears the fix either uncovered or created a different bug. I will close this issue and open a new one for the new bug,
