### ISSUE TITLE
Issues connecting via Stitchdata

### ISSUE THREAD

**Issue by suzybates** [singer-io/tap-harvest-forecast#4]
THANK YOU for creating this!  We have a home grown Forecast sync, so this will be much better!

I am not a developer, so I am trying to connect using the UI in Stitch Data only.

I created a Personal Access Token in HarvestID, used the ID in the Stitch Integration Settings, but I continue to get errors connecting.
`401 Client Error: Unauthorized for url: https://api.forecastapp.com/assignments`
any suggestions?

**Comment by KAllan357** [comment]
Hi @suzybates. I took a look at your connection and looked over some of our documentation for the [Harvest Forecast Integration](https://www.stitchdata.com/docs/integrations/saas/harvest-forecast).

It looks like you are receiving 401 Unauthorized error which indicates a permissions problem. Perhaps the account you used during the OAuth process does not permissions to access the Forecast API?

**Comment by suzybates** [comment]
I got it to work, you can close this.  This was a case of 'not reading all the directions'.  Sorry :(

**Comment by KAllan357** [comment]
Great!
